---
title: "Assignment 2"
author: "mzr"
date: "2024-09-25"
output: html_document
---
# 1. Data Wrangling

## 1.1 (Q1)
```{r}
library(tidyverse)
library(Stat2Data)
data("Hawks")
library(dplyr)
hSF <- Hawks %>% filter(Species == "RT" & Weight >= 1000) %>% select(Wing, Weight, Tail)
print(hSF)
head(hSF)

```
## 1.1 (Q2)
```{r}
n_examples <- nrow(hSF)
print(n_examples)
```
## 1.2 (Q1)
```{r}
hSF_sorted <- hSF %>% arrange(Wing)
top_five <- head(hSF_sorted, 5)
print(top_five)
```
## 1.3 (Q1)
```{r}
hawkSpeciesNameCodes <- data.frame(species_code = c("CH", "RT", "SS"), species_name_full = c("Cooper's", "Red-tailed", "Sharp-shinned"))
print(hawkSpeciesNameCodes)
```
## 1.3 (Q2)
```{r}
library(dplyr)
hawksFullName <- Hawks %>% left_join(hawkSpeciesNameCodes, by = c("Species" = "species_code")) %>% select(-Species) %>% rename(Species = species_name_full)
print(hawksFullName)
```
## 1.3 (Q3)
```{r}
top_seven <- hawksFullName %>% select(Species, Wing, Weight) %>% head(7)
print(top_seven)
```
## 1.4 (Q1)
```{r}
library(dplyr)
library(Stat2Data)
data("Hawks")
hawksWithBMI <- Hawks %>% mutate(bird_BMI = 1000 * (Weight / (Wing^2))) %>% select(Species, bird_BMI) %>% arrange(desc(bird_BMI))
top_eight <- head(hawksWithBMI, 8)
print(top_eight)
```
## 1.5 (Q1)
```{r}
library(dplyr)
summary_table <- hawksFullName %>% group_by(Species) %>% summarize(num_rows = n(), mn_wing = mean(Wing, na.rm = TRUE), md_wing = median(Wing, na.rm = TRUE), t_mn_wing = mean(Wing, trim = 0.1, na.rm = TRUE), b_wt_ratio = max(Wing / Tail, na.rm = TRUE))
print(summary_table)
```
## 1.5 (Q2)
```{r}
missing_summary <- hawksFullName %>% group_by(Species) %>% summarize(across(c(Wing, Weight, Culmen, Hallux, Tail, StandardTail, Tarsus, Crop), ~ sum(is.na(.), na.rm = TRUE), .names = "missing_{.col}"))
print(missing_summary)
```